package com.woniu.core.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.woniu.core.xmpp.rxbus.event.ChatMessageEvent;
import com.woniu.core.xmpp.rxbus.event.MessageTempEvent;

import com.woniu.core.dao.ChatMessageEventDao;
import com.woniu.core.dao.MessageTempEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageEventDaoConfig;
    private final DaoConfig messageTempEventDaoConfig;

    private final ChatMessageEventDao chatMessageEventDao;
    private final MessageTempEventDao messageTempEventDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageEventDaoConfig = daoConfigMap.get(ChatMessageEventDao.class).clone();
        chatMessageEventDaoConfig.initIdentityScope(type);

        messageTempEventDaoConfig = daoConfigMap.get(MessageTempEventDao.class).clone();
        messageTempEventDaoConfig.initIdentityScope(type);

        chatMessageEventDao = new ChatMessageEventDao(chatMessageEventDaoConfig, this);
        messageTempEventDao = new MessageTempEventDao(messageTempEventDaoConfig, this);

        registerDao(ChatMessageEvent.class, chatMessageEventDao);
        registerDao(MessageTempEvent.class, messageTempEventDao);
    }
    
    public void clear() {
        chatMessageEventDaoConfig.clearIdentityScope();
        messageTempEventDaoConfig.clearIdentityScope();
    }

    public ChatMessageEventDao getChatMessageEventDao() {
        return chatMessageEventDao;
    }

    public MessageTempEventDao getMessageTempEventDao() {
        return messageTempEventDao;
    }

}
